name: Go
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
    #- name: Build
    #  run: go build -v ./...
    #- name: Test
    #  run: go test -v ./...
    - name: build
      run: |
        node -e "console.log('package main; func flows() string { return \`'+JSON.stringify(require(require('path').join('.','examples','console.json'))+'\`}')" > flows.go
        go env -w GOOS=js GOARCH=wasm
        go build -o docs/console.wasm
        #echo "package main; func flows() string { return \`" > flows.go
        #cat examples/worldmap.json >> flows.go
        #echo "\`}" >> flows.go
        #go build -o docs/worldmap.wasm
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
    - name: release
      run: |
        go env -w GOOS=js GOARCH=wasm
        echo "package main; func flows() string { return \`" > flows.go
        cat examples/console.json >> flows.go
        echo "\`}" >> flows.go
        go build -o docs/console.wasm
        echo "package main; func flows() string { return \`" > flows.go
        cat examples/worldmap.json >> flows.go
        echo "\`}" >> flows.go
        go build -o docs/worldmap.wasm
        git config --global user.email "kazuhitoyokoi@nodered.jp"
        git config --global user.name "Kazuhito Yokoi"
        git add flows.go docs/*.wasm
        git commit -m "Update wasm files" || true
        git push
